apiVersion: extensions/v1beta1
kind: ReplicaSet
metadata:
  name: konfd
spec:
  replicas: 1
  selector:
    matchLabels:
      app: konfd
  template:
    metadata:
      labels:
        app: konfd
    spec:
      containers:
        - name: konfd
          image: "hbouvier/konfd:v0.0.4"
          imagePullPolicy: Always
          resources:
            requests:
              cpu: 100m
              memory: 30Mi
        - name: kubectl
          image: "gcr.io/google_containers/hyperkube:v1.4.6"
          command:
            - "/hyperkube"
          args:
            - "kubectl"
            - "proxy"
